name: ci
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install
      - name: Run Test with coverage
        run: yarn coverage
      - name: Upload test coverage artifact
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage
      - run: npx --yes coverage-badges-cli --output coverage/coverage-badges.svg
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: test
    if: "contains(github.ref, 'main')"
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js And Setup .npmrc
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope       : '@tomtsutom'
          always-auth : true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: install dependencies
        run: yarn install
      - name: build
        run: yarn build
      - name: publish
        run: npx --yes can-npm-publish --verbose && npm publish || echo "npm publish skipped"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
